version: '3.8'

services:
  headless-meeting-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: headless-meeting-bot:latest
    container_name: headless-meeting-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Required Zoom SDK credentials
      - ZOOM_SDK_KEY=${ZOOM_SDK_KEY}
      - ZOOM_SDK_SECRET=${ZOOM_SDK_SECRET}
      # Optional configuration
      - HTTP_ADDR=:8080
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      # Mount recordings directory for persistent storage
      - ./recordings:/app/recordings
      # Mount logs directory (if you want to persist logs)
      - ./logs:/app/logs
    networks:
      - meeting-bot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Security settings
    security_opt:
      - no-new-privileges:true
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

networks:
  meeting-bot-network:
    driver: bridge
